**IMPORTACIONES**

In [1]:
import pandas as pd
import itertools as it
import mysql.connector as conn
from sqlalchemy import create_engine

**CREACIÓN DE TABLAS DE COLORES POR FACCIÓN**

In [2]:
#COLOR DE LAS FACCIONES
color_cab = ['rubio', 'rubio ceniza', 'rubio platino', 'castano', 'castano claro', 'castano oscuro',\
            'chocolate', 'negro', 'pelirrojo', 'caoba']
color_ojos = ['miel', 'verde', 'ambar', 'almendra', 'azul', 'marron oscuro', 'negro', 'gris']
color_piel = ['moreno / marron claro', 'moreno claro / dorado', 'amarillento', \
              'negro', 'rosada', 'blanco / palido', 'melocoton']

In [3]:
data1 = {'ID' : [e for e in range(len(color_cab))], 'COLORES' : color_cab,  'TEMP' : 'temperatura', \
        'VALOR' : 'valores', 'TIPO' : 'cabello'}
data2 = {'ID' : [e for e in range(len(color_ojos))], 'COLORES' : color_ojos,  'TEMP' : 'temperatura', \
        'VALOR' : 'valores', 'TIPO' : 'ojos'}
data3 = {'ID' : [e for e in range(len(color_piel))], 'COLORES' : color_piel, 'TEMP' : 'temperatura', \
        'VALOR' : 'valores', 'TIPO' : 'piel'}

In [4]:
#TABLAS
cabello = pd.DataFrame(data1)
ojos = pd.DataFrame(data2)
piel = pd.DataFrame(data3)

Debemos diferenciar entre la temperatura, el valor y el croma de cada color de las facciones, siendo los siguientes:

  1. **TEMPERATURA**:
    
*frios* = ['castaño oscuro', 'chocolate', 'negro', 'rubio platino', 'rubio ceniza', 'rosada', 'blanco / pálido',
            'marrón oscuro', 'negro', 'azul', 'gris']
    
*calidos* = ['rubio', 'castaño', 'castaño claro', 'pelirrojo', 'moreno / marrón claro', 'moreno claro / dorado', 
              'amarillento','negro', 'melocotón', 'miel', 'verde', 'ámbar', 'almendra', 'caoba']

  2. **VALOR**:
 
*claro* = ['rubio', 'castaño', 'castaño claro', 'pelirrojo',
            'rubio platino', 'rubio ceniza', 'rosada', 'blanco /  pálido', 'amarillento', 'melocotón',
            'miel', 'verde', 'ámbar', 'azul', 'gris', 'almendra']
            
*oscuro* =['castaño oscuro', 'chocolate', 'negro', 'marrón oscuro', 'negro', 'moreno / marrón claro', 'moreno claro 
         dorado', 'negro', 'almendra', 'caoba']
  
   3. **CROMA**:
   
*brillante* - pieles, ojos y cabellos monocromáticos

*suave* - pieles, ojos y cabellos con policromáticos (mechas o reflejos, ojos con más de un color, etc.)

In [27]:
claro = ['rubio', 'castano', 'castano claro', 'pelirrojo', \
            'rubio platino', 'rubio ceniza', 'rosada', 'blanco /  palido', 'amarillento', 'melocoton', \
            'miel', 'verde', 'ambar', 'azul', 'gris']

oscuro = ['castaño oscuro', 'chocolate', 'negro', 'marrón oscuro', 'negro', 'moreno / marrón claro', \
         'moreno claro / dorado', 'negro', 'almendra', 'caoba']

In [28]:
frios = ['castano oscuro', 'chocolate', 'negro', 'rubio platino', 'rubio ceniza', 'rosada', 'blanco / palido',\
            'marron oscuro', 'negro', 'azul', 'gris']

calidos = ['rubio', 'castaño', 'castaño claro', 'pelirrojo', 'moreno / marrón claro', 'moreno claro / dorado',\
          'amarillento','negro', 'melocotón', 'miel', 'verde', 'ámbar', 'almendra', 'caoba']

In [6]:
#COLUMNA'TEMPERATURA' - CABELLO
frios = ['castano oscuro', 'chocolate', 'negro', 'rubio platino', 'rubio ceniza', 'rosada', 'blanco / palido',\
            'marron oscuro', 'negro', 'azul', 'gris']
temp1 = []
for e in cabello.COLORES:
    if e in frios:
        temp1.append('frio')
    else:
        temp1.append('calido')

cabello.TEMP = temp1

In [7]:
#COLUMNA'TEMPERATURA' - OJOS
temp1 = []
for e in ojos.COLORES:
    if e in frios:
        temp1.append('frio')
    else:
        temp1.append('calido')

ojos.TEMP = temp1

In [8]:
#COLUMNA'TEMPERATURA' - PIEL
temp1 = []
for e in piel.COLORES:
    if e in frios:
        temp1.append('frio')
    else:
        temp1.append('calido')

piel.TEMP = temp1

In [9]:
#COLUMNA 'VALOR' - CABELLO
claro = ['rubio', 'castano', 'castano claro', 'pelirrojo', \
            'rubio platino', 'rubio ceniza', 'rosada', 'blanco / palido', 'amarillento', 'melocoton', \
            'miel', 'verde', 'ambar', 'azul', 'gris']
temp2 = []
for e in cabello.COLORES:
    if e in claro:
        temp2.append('claro')
    else:
        temp2.append('oscuro')

cabello.VALOR = temp2

In [10]:
cabello

   ID         COLORES    TEMP   VALOR     TIPO
0   0           rubio  calido   claro  cabello
1   1    rubio ceniza    frio   claro  cabello
2   2   rubio platino    frio   claro  cabello
3   3         castano  calido   claro  cabello
4   4   castano claro  calido   claro  cabello
5   5  castano oscuro    frio  oscuro  cabello
6   6       chocolate    frio  oscuro  cabello
7   7           negro    frio  oscuro  cabello
8   8       pelirrojo  calido   claro  cabello
9   9           caoba  calido  oscuro  cabello

In [11]:
#COLUMNA 'VALOR' - OJOS
temp2 = []
for e in ojos.COLORES:
    if e in claro:
        temp2.append('claro')
    else:
        temp2.append('oscuro')

ojos.VALOR = temp2

In [12]:
ojos

   ID        COLORES    TEMP   VALOR  TIPO
0   0           miel  calido   claro  ojos
1   1          verde  calido   claro  ojos
2   2          ambar  calido   claro  ojos
3   3       almendra  calido  oscuro  ojos
4   4           azul    frio   claro  ojos
5   5  marron oscuro    frio  oscuro  ojos
6   6          negro    frio  oscuro  ojos
7   7           gris    frio   claro  ojos

In [13]:
#COLUMNA 'VALOR' - PIEL
temp2 = []
for e in piel.COLORES:
    if e in claro:
        temp2.append('claro')
    else:
        temp2.append('oscuro')

piel.VALOR = temp2

In [14]:
piel

   ID                COLORES    TEMP   VALOR  TIPO
0   0  moreno / marron claro  calido  oscuro  piel
1   1  moreno claro / dorado  calido  oscuro  piel
2   2            amarillento  calido   claro  piel
3   3                  negro    frio  oscuro  piel
4   4                 rosada    frio   claro  piel
5   5        blanco / palido    frio   claro  piel
6   6              melocoton  calido   claro  piel

In [15]:
#TABLA 'CROMA'
data4 = {'ID' : [1, 2], 'CROMA' : ['brillante', 'suave']}
croma = pd.DataFrame(data4)

Ahora, debemos diferenciar las diferentes paletas de colores que tendremos. Estas son:
    
   1. **PRIMAVERA** - CÁLIDA, CLARA, BRILLANTE
    
   2. **OTOÑO** - FRÍO, CLARO, SUAVE
   
   3. **VERANO** - CÁLIDO, OSCURO, BRILLANTE
    
   4. **INVIERNO** - FRÍO, OSCURO, BRILLANTE

Vamos a pasar las tablas a SQL ya que se nos facilita la combinación entre ellas

In [19]:
str_conn='mysql+pymysql://root:01051997Rm@localhost:3306/PROYECTO_FINAL'

cursor=create_engine(str_conn)

In [20]:
cabello.to_sql(name='cabello', con=cursor, if_exists='replace', index=False)
ojos.to_sql(name='ojos', con=cursor, if_exists='replace', index=False)
piel.to_sql(name='piel', con=cursor, if_exists='replace', index=False)
croma.to_sql(name='croma', con=cursor, if_exists='replace', index=False)

2

Traemos la tabla 'combinaciones' de MYSQL, ya que contiene todas las combinaciones posibles de colores de pelo, ojos y piel + los CROMAS

In [23]:
combinaciones = pd.read_csv('../PROYECTO_FINAL/DATA/combinaciones.csv', sep = ';')

In [25]:
#tenemos que limpiar un poco la base de datos de combinaciones ya que ha sufrido algunos cambios al pasar por MYSQL
combinaciones

     CABELLO  OJOS                   PIEL      CROMA
0      rubio  gris  moreno / marron claro      suave
1      rubio  gris  moreno / marron claro  brillante
2      rubio  gris  moreno claro / dorado      suave
3      rubio  gris  moreno claro / dorado  brillante
4      rubio  gris            amarillento      suave
...      ...   ...                    ...        ...
1115   caoba  miel                 rosada  brillante
1116   caoba  miel        blanco / palido      suave
1117   caoba  miel        blanco / palido  brillante
1118   caoba  miel              melocoton      suave
1119   caoba  miel              melocoton  brillante

[1120 rows x 4 columns]

In [26]:
def quitar_n(columna):
    valores = ['castano', 'castano claro', 'castano oscuro']
    if columna == 'castano':
        return 'castaño'
    elif columna == 'castano claro':
        return 'castaño claro'
    elif columna == 'castano oscuro':
        return 'castaño oscuro'